### ISSUE TITLE
Azure DevOps for build/release?

### ISSUE THREAD

**Issue by mohsinonxrm** [staticwebdev/react-basic#4]
@craigshoemaker , Any plans to allow Azure DevOps git based repos to deploy to Status Web Apps?

Also, is the limit to only support JavaScript/TypeScript Azure Functions due to GitHub Actions/Workflows? can they be replaced with C# from a separate build/release pipeline?

Guess I'll have to test it.

**Comment by craigshoemaker** [comment]
@mohsinonxrm - you can track product-related feature requests in the [static web apps repo](https://github.com/Azure/static-web-apps).

Right now [JavaScript is the only Functions language worker supported](https://docs.microsoft.com/en-us/azure/static-web-apps/apis#constraints), but that's independent of the GitHub integration.
